name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
    nuild:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Docker Hub Login
              run: echo "mypassword" | docker login -u talha9445 --password-stdin